#start the Action
name: Java CI with Maven

on:
  push:
    branches: [ devlopment ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
      
  security-check:

    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: trivy Installation
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg lsb-release curl
        sudo rm -f /etc/apt/sources.list.d/trivy.list
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | sudo tee /etc/apt/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
        sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y trivy
      
    - name: trivy fs scan
      run: trivy fs --format table -o fs-reports.json .
    - name: gitleaks installation
      run: sudo apt install gitleaks -y
    - name: Gitleaks Code Scan
      run: gitleaks detect source . -r gitleaks-reports.json -f json

      

